# Generated by Django 4.2.3 on 2023-09-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('accounts', '0002_barber_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='barber', to='cities.city', verbose_name='City'),
        ),
    ]
