# Generated by Django 4.2.3 on 2023-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_portfolio_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
    ]
